[project]
src = "src"
out = "out"
dot_env = ".env"
name = "fee-splitter-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["snekmate"]
default_network_name = "mainnet-fork"
cov_config = ".coveragerc"


[networks.mainnet-fork]
url = "${MAINNET_RPC_URL}"
explorer_uri = "https://api.etherscan.com/api/"
explorer_type = "etherscan"
explorer_api_key="${ETHERSCAN_TOKEN}"
chain_id = 1
fork = true


[networks.mainnet]
url = "${MAINNET_RPC_URL}"
explorer_uri = "https://api.etherscan.com/api/"
explorer_type = "etherscan"
explorer_api_key="${ETHERSCAN_TOKEN}"
chain_id = 1
fork = false


[networks.mainnet-fork.contracts.fee_collector]
address = "0xa2Bcd1a4Efbd04B63cd03f5aFf2561106ebCCE00"
abi_from_explorer = true

[networks.mainnet-fork.contracts.hooker]
address = "0x9A9DF35cd8E88565694CA6AD5093c236C7f6f69D"
abi_from_explorer = true

[networks.mainnet-fork.contracts.fee_distributor]
address = "0xD16d5eC345Dd86Fb63C6a9C43c517210F1027914"
abi_from_explorer = true

[networks.mainnet-fork.contracts.crvusd]
address = "0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E"
abi_from_explorer = true